2024-10-16 19:48:40,978 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "F:\School_Python\proba\tests_12_4.py", line 21, in test_run
    runner = Runner(12354)
             ^^^^^^^^^^^^^
  File "F:\School_Python\proba\run_exc.py", line 7, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-10-16 19:48:40,978 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "F:\School_Python\proba\tests_12_4.py", line 11, in test_walk
    runner = Runner('Sveta',-5)
             ^^^^^^^^^^^^^^^^^^
  File "F:\School_Python\proba\run_exc.py", line 12, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
